<?php

namespace App\Constants;

class DataFlag
{
    const TRANSACTION_FLAG_CLEARING = 1;
    const TRANSACTION_FLAG_GUARANTEE = 2;
    const TRANSACTION_FLAG_3DSECURE = 3;
    const TRANSACTION_FLAG_EXT_API = 4;
    const TRANSACTION_FLAG_DEMO = 5;
    const TRANSACTION_FLAG_AUTHORIZATION = 6;
    const TRANSACTION_FLAG_ACCRUAL = 7;
    const TRANSACTION_FLAG_STAKEHOLDER_EVALUATED = 8;
    const TRANSACTION_FLAG_BASKET_EVALUATED = 9;
    const TRANSACTION_FLAG_BASKET_ITEM_EVALUATED = 10;
    const TRANSACTION_FLAG_SECUCORE = 11;
    const TRANSACTION_FLAG_CHECKOUT = 12;
    const TRANSACTION_FLAG_LVP = 13;
    const TRANSACTION_FLAG_TRA = 14;
    const TRANSACTION_FLAG_MIT = 15;

    public static function getFlagName(int $flagId): ?string
    {
        $flags = [
            self::TRANSACTION_FLAG_CLEARING => 'TRANSACTION_FLAG_CLEARING',
            self::TRANSACTION_FLAG_GUARANTEE => 'TRANSACTION_FLAG_GUARANTEE',
            self::TRANSACTION_FLAG_3DSECURE => 'TRANSACTION_FLAG_3DSECURE',
            self::TRANSACTION_FLAG_EXT_API => 'TRANSACTION_FLAG_EXT_API',
            self::TRANSACTION_FLAG_DEMO => 'TRANSACTION_FLAG_DEMO',
            self::TRANSACTION_FLAG_AUTHORIZATION => 'TRANSACTION_FLAG_AUTHORIZATION',
            self::TRANSACTION_FLAG_ACCRUAL => 'TRANSACTION_FLAG_ACCRUAL',
            self::TRANSACTION_FLAG_STAKEHOLDER_EVALUATED => 'TRANSACTION_FLAG_STAKEHOLDER_EVALUATED',
            self::TRANSACTION_FLAG_BASKET_EVALUATED => 'TRANSACTION_FLAG_BASKET_EVALUATED',
            self::TRANSACTION_FLAG_BASKET_ITEM_EVALUATED => 'TRANSACTION_FLAG_BASKET_ITEM_EVALUATED',
            self::TRANSACTION_FLAG_SECUCORE => 'TRANSACTION_FLAG_SECUCORE',
            self::TRANSACTION_FLAG_CHECKOUT => 'TRANSACTION_FLAG_CHECKOUT',
            self::TRANSACTION_FLAG_LVP => 'TRANSACTION_FLAG_LVP',
            self::TRANSACTION_FLAG_TRA => 'TRANSACTION_FLAG_TRA',
            self::TRANSACTION_FLAG_MIT => 'TRANSACTION_FLAG_MIT',
        ];

        return $flags[$flagId] ?? null;
    }
}
